services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.gcloud.acme.tlschallenge=true"
      - "--certificatesresolvers.gcloud.acme.email=${GCE_SERVICE_ACCOUNT_EMAIL}"
      - "--certificatesresolvers.gcloud.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    environment:
      - "GCE_PROJECT=${GCE_PROJECT}"
      - "GCE_SERVICE_ACCOUNT_FILE=/run/secrets/gcloud.json"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    secrets:
      - source: gcloud_key
        target: gcloud.json
  gatus:
    image: twinproduction/gatus:latest
    restart: unless-stopped
    volumes:
      - /poc/gatus.yaml:/config/config.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gatus.rule=Host(`gatus.poc-vm.dados.rio`)"
      - "traefik.http.routers.gatus.entrypoints=websecure"
      - "traefik.http.routers.gatus.tls=true"
      - "traefik.http.routers.gatus.tls.certresolver=gcloud"
      - "traefik.http.services.gatus.loadbalancer.server.port=8080"
  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - /poc/grafana.ini:/etc/grafana/grafana.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.poc-vm.dados.rio`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=gcloud"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

volumes:
  grafana_data: {}
  letsencrypt: {}

secrets:
  gcloud_key:
    file: /poc/secrets/gcloud.json
