services:
  gatus:
    image: twinproduction/gatus:latest
    restart: unless-stopped
    volumes:
      - /poc/gatus.yaml:/config/config.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gatus.rule=Host(`gatus.poc-vm.dados.rio`)"
      - "traefik.http.routers.gatus.service=gatus"
      - "traefik.http.routers.gatus.entrypoints=web"
      - "traefik.http.services.gatus.loadbalancer.server.port=8080"
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.poc-vm.dados.rio`)"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    command:
      - "--api.insecure=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt_data:/letsencrypt

volumes:
  grafana_data: {}
  letsencrypt_data: {}
