version: "3.8"
services:
  gatus:
    image: twinproduction/gatus:latest
    restart: unless-stopped
    volumes:
      - ./gatus.yaml:/gatus.yaml
      - gatus_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gatus.rule=Host(`gatus.poc-vm.data.rio`)"
      - "traefik.http.routers.gatus.entrypoints=web"
      - "traefik.http.services.gatus.loadbalancer.server.port=8080"
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.poc-vm.data.rio`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - 443:443
      - 8080:8080
      - 80:80
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefic/traefik.yaml:ro

volumes:
  gatus_data: {}
  grafana_data: {}
