version: "3.8"
services:
  gatus:
    image: twinproduction/gatus:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./gatus.yaml:/gatus.yaml
      - gatus_data:/data
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  gatus_data: {}
  grafana_data: {}
