storage:
  type: memory

endpoints:
  - name: app-with-ingress
    url: "https://app.poc-k8s.dados.rio"
    conditions:
      - "[STATUS] == 200"

remote:
  instances:
    - endpoint-prefix: "poc-k8s-"
      url: "https://gatus.poc-k8s.dados.rio/api/v1/endpoints/statuses"
