- hosts: localhost
  become: true
  vars:
    service_account_key: "{{ lookup('env', 'SERVICE_ACCOUNT_KEY') }}"
    service_account_email: "{{ lookup('env', 'SERVICE_ACCOUNT_EMAIL') }}"
    gce_project: "{{ lookup('env', 'GCE_PROJECT') }}"

  roles:
    - geerlingguy.docker

  tasks:
    - name: Create secrets directory
      file:
        path: /poc/secrets
        state: directory
        mode: "0750"
        owner: root
        group: root

    - name: Write service account key
      copy:
        content: "{{ service_account_key }}"
        dest: /poc/secrets/gcloud.json
        mode: "0600"
        owner: root
        group: root

    - name: Run Docker Compose to launch services
      community.docker.docker_compose_v2:
        project_src: /poc
        state: present
      environment:
        GCE_PROJECT: "{{ gce_project }}"
        GCE_SERVICE_ACCOUNT_EMAIL: "{{ service_account_email }}"
