- hosts: localhost
  become: true

  roles:
    - geerlingguy.docker

  tasks:
    - name: Run Docker Compose to launch services
      community.docker.docker_compose_v2:
        project_src: /poc
        state: present
