tfplan := "terraform.tfplan"
tfvars := "terraform.tfvars"
bucket := "bucket=datario-terraform"

default: plan apply

@auth:
    gcloud auth application-default login
    gcloud auth login

@init:
    terraform init -backend-config {{bucket}} -upgrade

@plan:
    terraform plan -var-file {{tfvars}} -out {{tfplan}}

@apply:
    terraform apply {{tfplan}}

@destroy:
    terraform destroy -var-file {{tfvars}}
