fullnameOverride: prometheus
cleanPrometheusOperatorObjectNames: true

alertmanager:
  enabled: false

grafana:
  enabled: false

kubelet:
  serviceMonitor:
    metricRelabelings:
      - action: replace
        sourceLabels:
          - node
        targetLabel: instance

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: ${issuer}
    hosts:
      - ${domain}
    paths:
      - /
    pathType: Prefix
    tls:
      - hosts:
          - ${domain}
        secretName: ${domain_tls_secret}
  prometheusSpec:
    enableRemoteWriteReceiver: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50G
          storageClassName: standard
    additionalArgs:
      - name: web.enable-otlp-receiver
        value: ""
    remoteWrite:
      - url: "${url}:9090/api/v1/write"
